up:
@COMPOSE_PROJECT_NAME=achuprin /
COMMENT_TAG=logging /
UI_TAG=logging /
POST_TAG=logging /
USERNAME=achuprin /
MONGO_VERSION=3.2 /
UI_HOST_PORT=9292 /
UI_CONTAINER_PORT=9292 /
	docker-compose -f ../../docker/docker-compose.yml up -d
.PHONY: up
