name: terraform
on:
  push:
    branches: main
  pull_request:

jobs:
  terraform-stage:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/stage

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform fmt check
        id: fmt-check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform fmt
        id: fmt
        run: terraform fmt


      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
  terraform-prod:
      runs-on: ubuntu-latest

      defaults:
        run:
          working-directory: ./terraform/prod

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: HashiCorp - Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.0

        - name: Terraform fmt check
          id: fmt-check
          run: terraform fmt -check
          continue-on-error: true

        - name: Terraform fmt
          id: fmt
          run: terraform fmt


        - name: Terraform Init
          id: init
          run: terraform init

        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color
